import 'dart:typed_data';

import 'package:eagleflow/core/utils/pdf_share_helper.dart';
import 'package:eagleflow/features/quotations/application/quotation_controller.dart';
import 'package:eagleflow/features/quotations/domain/quotation_defaults.dart';
import 'package:eagleflow/features/quotations/presentation/quotation_preview_screen.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:share_plus/share_plus.dart';

void main() {
  const fallbackMessage =
      "File sharing isn't supported in this browser. "
      'The PDF was downloaded instead.';

  Future<void> pumpPreview(
    WidgetTester tester, {
    required Uint8List generatedBytes,
    required PdfShareHelper shareHelper,
    required Future<String?> Function(Uint8List, String) saver,
  }) async {
    final quotation = QuotationDefaults.createEmptyDraft().copyWith(
      quotationNumber: 'QT/123',
    );

    await tester.pumpWidget(
      MaterialApp(
        onGenerateRoute: (settings) => MaterialPageRoute<void>(
          settings: RouteSettings(arguments: QuotationController(quotation)),
          builder: (_) => QuotationPreviewScreen(
            pdfGenerator: (_) async => generatedBytes,
            pdfSaver: saver,
            pdfShareHelper: shareHelper,
          ),
        ),
      ),
    );
    await tester.pump();
  }

  Future<void> selectSharePdf(WidgetTester tester) async {
    await tester.tap(find.byTooltip('Export'));
    await tester.pumpAndSettle();
    await tester.tap(find.text('Share PDF'));
    await tester.pumpAndSettle();
  }

  testWidgets('Share PDF shares generated bytes without downloading', (
    tester,
  ) async {
    final bytes = Uint8List.fromList([1, 2, 3]);
    Uint8List? sharedBytes;
    String? sharedFilename;
    var saveCalls = 0;
    final shareHelper = PdfShareHelper(
      share: (params) async {
        sharedBytes = await params.files!.single.readAsBytes();
        sharedFilename = params.fileNameOverrides!.single;
        return ShareResult.unavailable;
      },
    );

    await pumpPreview(
      tester,
      generatedBytes: bytes,
      shareHelper: shareHelper,
      saver: (_, _) async {
        saveCalls++;
        return 'unused';
      },
    );
    await selectSharePdf(tester);

    expect(sharedBytes, bytes);
    expect(sharedFilename, 'QT_123.pdf');
    expect(saveCalls, 0);
    expect(find.text(fallbackMessage), findsNothing);
  });

  testWidgets('Share PDF downloads and explains fallback when sharing fails', (
    tester,
  ) async {
    final bytes = Uint8List.fromList([4, 5, 6]);
    Uint8List? savedBytes;
    String? savedFilename;
    final shareHelper = PdfShareHelper(
      share: (_) async => throw Exception('Sharing unsupported'),
    );

    await pumpPreview(
      tester,
      generatedBytes: bytes,
      shareHelper: shareHelper,
      saver: (pdfBytes, filename) async {
        savedBytes = pdfBytes;
        savedFilename = filename;
        return 'Downloaded to browser';
      },
    );
    await selectSharePdf(tester);

    expect(savedBytes, bytes);
    expect(savedFilename, 'QT_123.pdf');
    expect(find.text(fallbackMessage), findsOneWidget);
  });
}
